### ISSUE TITLE
Python 3.6 / PostgreSQL 9.6 Deprecation Checklist / Chores

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#11552]
- [x] Bump the version of Black we use for code formatting
- [x] Bump the `tool.black.target-version` in pyproject.toml
- [x] Run Black on all the things
- [x] Update our Trove classifiers to drop support for 3.6
- [x] Update CI configuration to stop testing on 3.6 (including updating the `olddeps` test run)
- [x] Update .deb build script to stop building for Ubuntu Bionic (18.04) ~~and Ubuntu Hirsute (21.04)~~
- [x] Get rid of the SyTest image that uses Bionic (and figure out what to replace it with)
- [x] Grep source and docs for anything referencing Python 3.6, Bionic, or Hirsute and excise it
- [x] Run pyupgrade
- [ ] ~~Consider taking advantage of `from __future__ import annotations` from [PEP 563](https://docs.python.org/3.10/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations) to speed up application start?~~
- [x] Get rid of anything referencing PostgreSQL 9.6; our new minimum version is 10. (Check SyTest too)

**Comment by richvdh** [comment]
>  Update .deb build script to stop building for Ubuntu Bionic (18.04) and Ubuntu Hirsute (21.04)

In theory we could support these versions of ubuntu via deadsnakes (https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa). I'm conscious that 21.04 is still the current LTS version of ubuntu, so is probably quite popular. (It's what I use on my dev box, which is going to make things interesting...)

**Comment by callahad** [comment]
> In theory we could support these versions of ubuntu via deadsnakes

Individuals are absolutely welcome to continue running Synapse on older Ubuntu releases, including via the deadsnakes PPA, but the Synapse team itself will not build third party Debian packages for those releases.

> I'm conscious that 21.04 is still the current LTS version of ubuntu

It's not :) 20.04 (Focal) is the current LTS, and we will still support it.

21.04 (Hirsute) is a normal release which hits end-of-life on January 1st:

![Ubuntu release lifecycle graph](https://user-images.githubusercontent.com/24193/145558641-ed7efdd5-1dfa-4215-99f8-c945184d6b39.png)

**Comment by richvdh** [comment]
> >     I'm conscious that 21.04 is still the current LTS version of ubuntu
>
> It's not :) 20.04 (Focal) is the current LTS, and we will still support it.

ohh, sorry, my mistake. More coffee needed.

In fairness, I think you introduced confusion by talking about dropping support for 21.04. That's fine, and a thing to do as per our support policy, but it's completely orthogonal to dropping support for python 3.6 (and it's already covered by https://github.com/matrix-org/synapse/issues/11525).

**Comment by richvdh** [comment]
For the record:

 * Postgres 9.6 is unsupported upstream as of [11 Nov 2021](https://endoflife.date/postgresql)
 * Python 3.6 is unsupported upstream as of [23 Dec 2021](https://endoflife.date/python)

**Comment by clokep** [comment]
Another task we should be able to do:

* [ ] Drop using the `mock` backport (to get support for `AsyncMock`). We also might be able to clean-up some of the usages of `make_awaitable`, etc.

**Comment by DMRobertson** [comment]
>  Consider taking advantage of from __future__ import annotations from PEP 563 to speed up application start?

[This comment](https://github.com/python-attrs/attrs/issues/313#issuecomment-422164226) suggests that `from __future__ import annotations` would allow us to define generic attrs slots classes that don't error at runtime.

**Comment by H-Shay** [comment]
After a brief consultation we decided adding the `from __future__ import annotations` was a bit of a faff for unclear gain so it has been removed from the list.

**Comment by ShadowJonathan** [comment]
Maybe [pyupgrade](https://github.com/asottile/pyupgrade) as well?

**Comment by clokep** [comment]
> Maybe [pyupgrade](https://github.com/asottile/pyupgrade) as well?

Already in the checklist (and done) in #11685

**Comment by ShadowJonathan** [comment]
Whoops, I did not notice, thanks!

**Comment by H-Shay** [comment]
I think all these tasks are done and merged, so I will close this issue!
