### ISSUE TITLE
Support Matrix 1.4

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#13954]
Matrix 1.4 was just released, we should break down a list of things that Synapse needs to support it. See the release notes: https://matrix.org/blog/2022/09/29/matrix-v-1-4-release#client-server-api

Depends on #13953

----

## Client-Server API

* [x] Remove unused policy room sharing mechanism, as per MSC3844.
* [x] Add a `.m.rule.room.server_acl` push rule to match m.room.server_acl events, as per MSC3786. #12601, #13997
* [x] Add `Cross-Origin-Resource-Policy` (CORP) headers to media repository, as per MSC3828. #12944
* [x] Copy a room's `type` when upgrading it, as per MSC3818. #12786
* [x] Add `room_types` filter and `room_type` response to `/publicRooms`, as per MSC3827. #13031
* [x] Add `m.replace` relations (event edits), as per MSC2676. #12793, #12503
* [x] Add `m.read.private` receipts, as per MSC2285.
* [x] Make `m.fully_read` optional on `/read_markers`, as per MSC2285.
* [x] Allow `m.fully_read` markers to be set from `/receipts`, as per MSC2285.
* [x] Add threading via `m.thread` relations, as per MSC3440, MSC3816, MSC3856, and MSC3715. #13394
* [x] Add per-thread notifications and read receipts, as per MSC3771 and MSC3773. #12550

## Server-Server API

* [x] Add per-thread notifications and read receipts, as per MSC3771 and MSC3773. #12550

## Application Service API

* [x] Replace homeserver authorization approach with an `Authorization` header instead of `access_token` when talking to the application service, as per MSC2832. #13996
