### ISSUE TITLE
Profile /messages and make it faster

### ISSUE THREAD

**Issue by kittykat** [matrix-org/synapse#14284]
Message history can be very slow to load. Users expect to be able to rapidly load scrollback within a room, infinite scrolling without having to wait for the server to load more messages.

Relevant milestones:
- [Q4 milestones](https://github.com/matrix-org/synapse/milestone/11)

These tasks need to be completed for this issue to be closed:

- [x] https://github.com/matrix-org/synapse/issues/14108
- [x] https://github.com/matrix-org/synapse/issues/13624
- [x] https://github.com/matrix-org/synapse/issues/13929
- [x] https://github.com/matrix-org/synapse/issues/13856
- [x] https://github.com/matrix-org/synapse/issues/13622
- [x] https://github.com/matrix-org/synapse/issues/13621
- [x] https://github.com/matrix-org/synapse/issues/13626

**Comment by kittykat** [comment]
@MadLittleMods Do you have any thoughts on how much more improvement can be made here with the remaining open issues?

**Comment by MadLittleMods** [comment]
@kittykat Maybe down to ~10s. https://github.com/matrix-org/synapse/issues/13623 and https://github.com/matrix-org/synapse/issues/13619 would help make our numbers more consistent. https://github.com/matrix-org/synapse/issues/13620 would be a general nice win for federation traffic.

**Comment by kittykat** [comment]
Follow on tasks split out into #15182
