### ISSUE TITLE
Profile /messages and make it even faster

### ISSUE THREAD

**Issue by kittykat** [matrix-org/synapse#15182]
Message history can be very slow to load. Users expect to be able to rapidly load scrollback within a room, infinite scrolling without having to wait for the server to load more messages.

This is the follow on task from the Q4 one: #14284

These tasks need to be completed for this issue to be closed:

- [ ] https://github.com/matrix-org/synapse/issues/13356
- [ ] https://github.com/matrix-org/synapse/issues/13623
- [ ] https://github.com/matrix-org/synapse/issues/13619
- [ ] https://github.com/matrix-org/synapse/issues/13700
- [ ] https://github.com/matrix-org/synapse/issues/13620
- [ ] https://github.com/matrix-org/synapse/issues/13625
- [ ] https://github.com/matrix-org/synapse/issues/13659
- [ ] https://github.com/matrix-org/synapse/issues/13676

**Comment by erikjohnston** [comment]
Closing this as we're not actively working on this anymore
