### ISSUE TITLE
Bring (experimental) Synapse support for delegated auth to an official release

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/synapse#15573]
* [x] Admin API to provision users: https://github.com/matrix-org/synapse/pull/15611
* [ ] Initial delegation support: https://github.com/matrix-org/synapse/pull/15582
* [ ] Synapse reverse proxying to the auth server

We'll eventually want some follow-ups too:

* [ ] Appservice support
* [ ] Documentation
* [ ] Better configuration errors
* [ ] Handle TODO comments

**Comment by clokep** [comment]
@sandhose is taking care of this, but GitHub isn't letting me assign them.
