### ISSUE TITLE
Resolve mypy type lints when running with Python 3.8 (minimum supported version)

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#15603]
*Spawning from https://github.com/matrix-org/synapse/pull/15602,* where we should be running `mypy` with our minimum supported Python version since later versions can include overloads, etc which aren't backwards compatible.

Before we can actually [merge the PR which updates the CI to use Python 3.8](https://github.com/matrix-org/synapse/pull/15602), we have to resolve the lints that pop up first so we don't just have a broken CI after merging https://github.com/matrix-org/synapse/pull/15602

### TODO  Python 3.8

 - [x] [`synapse/app/_base.py:217`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/app/_base.py#L217): `error: Missing positional arguments "value", "tb" in call to "format_exception"  [call-arg]`
    - https://github.com/matrix-org/synapse/pull/15599
 - [x] [`synapse/app/_base.py:217`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/app/_base.py#L217): `error: Argument 1 to "format_exception" has incompatible type "Exception"; expected "Optional[Type[BaseException]]"  [arg-type]`
    - https://github.com/matrix-org/synapse/pull/15599
 - [x] [`synapse/storage/controllers/stats.py:58`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/storage/controllers/stats.py#L58): `error: "Counter" is not subscriptable, use "typing.Counter" instead  [misc]`
    - https://github.com/matrix-org/synapse/pull/15604
 - [x] [`tests/test_state.py:267`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/test_state.py#L267): `error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]`
    - https://github.com/matrix-org/synapse/pull/15604

### ~~TODO Python 3.7~~

<details>
<summary>We're no longer trying to target Python 3.7 given that EOL is weeks away (wasted effort)</summary>

 - [ ] [`docker/configure_workers_and_start.py:56`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/docker/configure_workers_and_start.py#L56): `error: Module "typing" has no attribute "SupportsIndex"; maybe "SupportsRound"?  [attr-defined]`
 - [ ] [`synapse/util/check_dependencies.py:33`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/util/check_dependencies.py#L33): `error: Unused "type: ignore" comment`
 - [ ] [`synapse/util/check_dependencies.py:200`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/util/check_dependencies.py#L200): `error: Unused "type: ignore" comment`
 - [ ] [`synapse/config/_base.pyi:2`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/config/_base.pyi#L2): `error: Module "typing" has no attribute "Literal"  [attr-defined]`
    - https://github.com/matrix-org/synapse/pull/15605
 - [ ] [`synapse/config/_base.pyi:170`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/config/_base.pyi#L170): `error: Overloaded function signature 2 will never be matched: signature 1's parameter type(s) are the same or broader  [misc]`
 - [ ] [`synapse/app/_base.py:217`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/app/_base.py#L217): `error: Missing positional arguments "value", "tb" in call to "format_exception"  [call-arg]`
    - https://github.com/matrix-org/synapse/pull/15599
 - [ ] [`synapse/app/_base.py:217`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/app/_base.py#L217): `error: Argument 1 to "format_exception" has incompatible type "Exception"; expected "Optional[Type[BaseException]]"  [arg-type]`
    - https://github.com/matrix-org/synapse/pull/15599
 - [ ] [`synapse/storage/controllers/stats.py:58`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/storage/controllers/stats.py#L58): `error: "Counter" is not subscriptable, use "typing.Counter" instead  [misc]`
    - https://github.com/matrix-org/synapse/pull/15604
 - [ ] [`tests/test_utils/__init__.py:39`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/test_utils/__init__.py#L39): `error: Module "sys" has no attribute "UnraisableHookArgs"  [attr-defined]`
 - [ ] [`tests/test_utils/__init__.py:92`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/test_utils/__init__.py#L92): `error: Module has no attribute "unraisablehook"  [attr-defined]`
 - [ ] [`synapse/_scripts/synapse_port_db.py:1171`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/_scripts/synapse_port_db.py#L1171): `error: Name "curses.window" is not defined  [name-defined]`
 - [ ] [`synapse/_scripts/synapse_port_db.py:1375`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/synapse/_scripts/synapse_port_db.py#L1375): `error: Name "curses.window" is not defined  [name-defined]`
 - [ ] [`tests/test_state.py:267`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/test_state.py#L267): `error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]`
    - https://github.com/matrix-org/synapse/pull/15604
 - [ ] [`tests/metrics/test_metrics.py:22`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/metrics/test_metrics.py#L22): `error: Unused "type: ignore" comment`
 - [ ] [`tests/http/federation/test_srv_resolver.py:90`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/http/federation/test_srv_resolver.py#L90): `error: Incompatible types in assignment (expression has type "object", variable has type "List[Server]")  [assignment]`
 - [ ] [`tests/http/federation/test_srv_resolver.py:92`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/http/federation/test_srv_resolver.py#L92): `error: Unused "type: ignore" comment`
 - [ ] [`tests/http/federation/test_srv_resolver.py:119`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/http/federation/test_srv_resolver.py#L119): `error: Incompatible types in assignment (expression has type "object", variable has type "List[Server]")  [assignment]`
 - [ ] [`tests/http/federation/test_srv_resolver.py:121`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/http/federation/test_srv_resolver.py#L121): `error: Unused "type: ignore" comment`
 - [ ] [`tests/http/federation/test_srv_resolver.py:154`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/http/federation/test_srv_resolver.py#L154): `error: Incompatible types in assignment (expression has type "object", variable has type "List[Server]")  [assignment]`
 - [ ] [`tests/http/federation/test_srv_resolver.py:156`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/tests/http/federation/test_srv_resolver.py#L156): `error: Unused "type: ignore" comment`

</details>

### Dev notes

Find/replace from the `mypy` output to generate that list:

Find:
```
^(.*):(\d+): (.*)$
```

Replace:
```
 - [ ] [`$1:$2`](https://github.com/matrix-org/synapse/blob/ba572647b291e593e70a30e45c234c9766472ff3/$1#L$2): `$3`
```

**Comment by MadLittleMods** [comment]
Closing as all of the linked PR's are now merged and the mypy CI pass on https://github.com/matrix-org/synapse/pull/15602 is now passing :white_check_mark:
