### ISSUE TITLE
Support for consent for privacy policies

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3197]
As part of the work on [GDPR compliance](https://github.com/vector-im/riot-meta/issues/149), we need support for gathering users' consent before they can use the platform.

Steps here will include:
* [x] Add a column to the `users` table recording consent (done in #3213)
* [x] Add support for serving up a (templated, configurable) consent page. Users will get personalised links so that we know who is giving consent without them having to log in. (done in #3213)
* [x] Wire up the consent page to record consent in the db. (done in #3213)
* [x] Create an AS-like service which opens a DM with new users after they register, and sends them the link to their consent page. This will also be useful for finally fixing https://github.com/matrix-org/synapse/issues/1199 aka SYN-1. (#3236)
* [ ] Scripts to trawl the existing user list and send them their links via:
  * ~~DM via the server bot~~ (done via #3236)
  * [ ] email (if we have their address)
  * [ ] push
* [x] The (configurable) ability to block usage of the server until the user has consented. (#3257) "Usage" includes:
  * [x] Creating rooms
  * [x] Joining rooms
  * [x] Sending events
  

Extensions:
* [ ] i18n support for consent page
* [ ] A front-end page which gathers login creds from a user and directs them to their personalised consent page, so that we can post the link in public.

**Comment by turt2live** [comment]
An additional configuration option for "yes, I really do want to disable consent gathering because I really want to" would be nice. Use case being a server that gathers consent elsewhere or just doesn't want to (at their own risk). "Elsewhere" could be an employee contract, etc.

**Comment by Half-Shot** [comment]
Or just a personal server? I trust my family not to sue me :)

**Comment by richvdh** [comment]
yup consent gathering will be disabled unless explicitly configured.

**Comment by ara4n** [comment]
Other stuff to consider:
* The “server messages” DM should probably be unrejectable and unleaveable.
* The consent url could be sent in a custom event type (or with some sort of other metadata) so that smarter clients can display it as a modal? Although this would need careful thought to avoid phishing
* The error message served up whenever an unconsented user tries to send us data should include a link to the consent page so API devs and naive clients are pointed in the right direction
* If the user explicitly rejects consent we should do a gdpr erase on whatever data we have gathered so far for that account (presumably mxid, 3pids, etc)

**Comment by turt2live** [comment]
> The consent url could be sent in a custom event type

Would be a good time to try and shove human representable events into the public eye to see how it goes.

**Comment by lampholder** [comment]
Another item - the consent page should render slightly differently if consent has already been provided (with the checkboxes checked and greyed out, and an explanation of what to do if the user no longer wants their data to be processed).

**Comment by richvdh** [comment]
well, I think we've done everything here that is going to make it into synapse 0.30, so I'm going to close this.

**Comment by rubo77** [comment]
I added the advanced consent page template in my branch here at https://github.com/rubo77/synapse/blob/privacy_template/docs/privacy_policy_templates/en/1.0.html

I got it from matrix, when I accepted my consent there.

maybe this could find its way into this synapse docs too?
