### ISSUE TITLE
[Meta] Divergence from the spec

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3506]
This is a new issue for https://github.com/matrix-org/synapse/issues/2603

Known issues:
* [ ] https://github.com/matrix-org/synapse/issues/3162 / https://github.com/matrix-org/synapse/issues/1254
* [x] https://github.com/matrix-org/synapse/issues/2644
* [x] https://github.com/matrix-org/synapse/issues/2604
* [x] https://github.com/matrix-org/synapse/issues/2602
* [x] https://github.com/matrix-org/synapse/issues/2349 (fixed by https://github.com/matrix-org/synapse/issues/2986)
* [x] https://github.com/matrix-org/matrix-doc/pull/1081 (split from https://github.com/matrix-org/matrix-doc/issues/1052)
* [x] https://github.com/matrix-org/matrix-doc/pull/1080 (split from https://github.com/matrix-org/matrix-doc/issues/1052)
* [x] https://github.com/matrix-org/matrix-doc/issues/1045
* [ ] https://github.com/matrix-org/synapse/issues/4173
* [ ] https://github.com/matrix-org/synapse/issues/4175
* [ ] https://github.com/matrix-org/synapse/issues/4236
* [ ] https://github.com/matrix-org/synapse/issues/4268
* [x] https://github.com/matrix-org/synapse/issues/5280 - heavily arguable - see issue
* [ ] https://github.com/matrix-org/synapse/issues/5665

**Comment by turt2live** [comment]
> ma1uta has also started a list at https://github.com/ma1uta/jeon/blob/master/SpecDiff.md

([source](https://github.com/matrix-org/synapse/issues/2603#issuecomment-395529223))

**Comment by richvdh** [comment]
I wonder if we need this issue, rather than just using the 'spec compliance' label (https://github.com/matrix-org/synapse/labels/spec%20compliance

**Comment by clokep** [comment]
That seems easier to keep up-to-date. I added the "spec compliance" label to the issues in the description that are still open.
