### ISSUE TITLE
Convert inlineCallbacks to async/await

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#7988]
There's a desire to convert code that uses `inlineCallbacks` to `async` / `await` since it makes stack traces nicer and helps with profiling (e.g. #7670).

Some progress on this can be tracked at https://patrick.cloke.us/areweasyncyet/

I've broken down the Synapse code into modules for tracking of this work:

* [ ] `contrib.cmdclient`
* [ ] `contrib.experiments`
* [x] `docs.log_contexts` #10353
* [ ] `scripts.synapse_port_db` #6718
* [x] `synapse.api` #7363 #8031
* [ ] `synapse.app` #7620 #7868 #8213
* [x] `synapse.appservice` #7973 #8207
* [x] `synapse.crypto` #8003
* [x] `synapse.events` #7949
* [ ] `synapse.federation` #5689 #6279 #6280 #6840 #6996 #7363 #7868 #7975 #8072
* [x] `synapse.groups` #7363 #7600 #7951
* [ ] `synapse.handlers` #6275 #6280 #6484 #6496 #6504 #6517 #6559 #6837 #6991 #7261 #7338 #7363 #7396 #7459 #7460 #7507 #7557 #7561 #7640 #7649 #7678 #7679 #7727 #7775 #7851 #7860 #7871 #7884 #7912 #7935 #7939 #7945 #7950
* [ ] `synapse.http` #5475 #5585 #7874 #7975 #8016 #8214
* [ ] `synapse.logging` #7872
* [ ] `synapse.metrics` #8032
* [x] `synapse.module_api`
* [ ] `synapse.notifier` #7395
* [x] `synapse.push` #7557 #7948 #7981
* [x] `synapse.replication` #6274 #6666 #7987
* [x] `synapse.rest` #6196 #6482 #6483 #7020 #7110 #7873 #7947 #8027
* [x] `synapse.server`
* [x] `synapse.server_notices` #7363 #7394 #7996
* [x] `synapse.spam_checker_api`
* [x] `synapse.state` #7942 #8140
* [x] `synapse.storage` #6647 #7241 #7363 #7620 #7963 #7976 #8042 #8045 #8061 #8062 #8063 #8066 #8069 #8070 #8071 #8074 #8075 #8076 #8087 #8100 #8121 #8133 #8156 #8162 #8166 #8168 #8173 #8191 #8192 #8194 #8195 #8197 #8199 #8200 #8201
* [x] `synapse.streams` #8014
* [ ] `synapse.util` #6291 #6836 #8035 #8119 #8202 #8215
* [x] `synapse.visibility` #7951
* [ ] `tests.api` #9396
* [ ] `tests.appservice`
* [ ] `tests.crypto`
* [ ] `tests.federation`
* [ ] `tests.handlers` #9377 #9396
* [ ] `tests.http`
* [ ] `tests.replication`
* [ ] `tests.rest` #9377 #9396
* [ ] `tests.server`
* [ ] `tests.server_notices`
* [ ] `tests.state`
* [ ] `tests.storage` #8193 #9736
* [ ] `tests.test_federation`
* [x] `tests.test_server`
* [ ] `tests.test_state`
* [x] `tests.test_utils` #8261
* [ ] `tests.test_visibility`
* [ ] `tests.unittest`
* [ ] `tests.util`
* [ ] `tests.utils`

**Comment by clokep** [comment]
I should mention that if anyone is interested in helping out here they can poke me here or in #synapse-dev:matrix.org

**Comment by clokep** [comment]
To give a bit of a higher level update here:

* Most non-test modules have been converted to use async/await, there's also a few PRs outstanding (notably for `runInteraction`).
* Most tests need to be switched from using `defer.inlineCallbacks` style to use `get_success()`.
* There's probably some documentation that needs to be updated.
* It would be nice to see if some `ensureDeferred` calls could be removed (since that seems to make `inlineCallback` objects).

**Comment by clokep** [comment]
The current work on this is done, but I wanted to give another update:
* The vast majority of the code has been converted from `inlineCallbacks` to `async`.
* There are a few remaining bits that could be converted, it is probably worth doing those, but at a much lower effort than we spent so far on this.
* Generally methods that return an awaitable are now `async` and `await` on other calls instead of passing through awaitables from other calls.
* There are remaining uses of `ensureDeferred`, which has the unfortunate side-effect of converting `async` to `inlineCallbacks`.
* The tests need a lot of updating, in particular the use of tests being defined as `inlineCallbacks` and then using `yield` should be replaced with `self.get_success`, but this requires the test case inheriting from `HomeserverTestCase`, which not all tests use. This would be a great way to contribute if someone is interested!

**Comment by clokep** [comment]
As this isn't actively being worked on I'm not sure having a tracking issue for this makes sense anymore. The https://patrick.cloke.us/areweasyncyet/ page was updated as of yesterday (and is easy enough to keep up-to-date).

I think *most* of the remaining bits are converting the tests to use` HomeserverTestCase` + `get_success` instead of marking the test as `inlineCallbacks` and `yield`-ing each `Deferred`. This is tedious, although not particularly hard. It also isn't particularly urgent since the gains from it are minor.

I think most of the remaining uses in the `synapse` package probably need to be kept in order to interface with Twisted APIs, although there might be a few more that could go away.
