### ISSUE TITLE
[tracker] flake8-bugbear progression

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9366]
This is a tracker issue for adding [flake8-bugbear](https://pypi.org/project/flake8-bugbear/) in short steps, and to keep track of it's progress.

The original PR was #9320, it has been split in the following PRs;

- [x] ~~Add `flake8-bugbear` dependency, put `B00` in ignore list, and fix remaining violations (#9499)~~
- [x] Finish check-fixing PRs (in order of altering `ignore` keys): 
  - [x] ~~`B00` -> `B006,B007,B008`: #9659~~
  - [x] ~~`B006,B007,B008` -> `B007`: #9682~~
  - [x] ~~`B007` -> `""`: #9838~~
- [ ] Discuss and merge making flake8 explicitly `select` checks (issue #XXXX, PR #XXXX)
  - [ ] Add one `B` code on `select=` (#XXXX)
  - [ ] Enable opinionated checks (`B90`) (#XXXX)
- [ ] (Side-quest) Update bugbear to [21.4](https://github.com/PyCQA/flake8-bugbear/releases/tag/21.4.1) (which adds a new check) (#XXXX)

(Some more information in #9279 about some specifics of these checks)

(#9370 was originally part of this tracker issue, but was denied, [some discussion followed](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$Rx9vt5oTauoF21aNQhfSP67FN5RstYhqO6aiUXp_C2c?via=matrix.org&via=vector.modular.im&via=envs.net))

**Comment by ShadowJonathan** [comment]
Optionally i'd also like to enable `B90`, (as said in #9279), or a select few of these checks, these can happen after the second PR, but just to note that.

**Comment by ShadowJonathan** [comment]
(made #9368 and 9369 to be deliberated for after the first PR)

**Comment by clokep** [comment]
@ShadowJonathan Looks like a lot of this is done! 🎉 Any update on here that we should add?

**Comment by ShadowJonathan** [comment]
Already added all those updates, next step is "Discuss and merge making flake8 explicitly select checks", i'll make a properly-worded Process issue for that whenever i have time, currently bugbear is "there", but i'd like to also enable some of those "opinionated" checks.

Additionally, I'd wanna update bugbear to the latest version, to fix the newest checks that were added, lemme add that one now...

**Comment by clokep** [comment]
> Process issue for that whenever i have time, currently bugbear is "there", but i'd like to also enable some of those "opinionated" checks.

I think we can just use this issue.

**Comment by ShadowJonathan** [comment]
> I think we can just use this issue.

no, because in `#synapse-dev` we talked about process issues/changes, which i would *really* like to be discussed on its own merit.

This is simply a tracker issue too, I dont think it is adequate or on-topic to start talking about something like this on here.

**Comment by ShadowJonathan** [comment]
https://github.com/matrix-org/synapse/pull/12600 came to the conclusion that [`extend-select`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-extend-select) was recently added, which addresses the whole deal with `select=`.

I'll think about adding B90 lints in the future, but for now, this is done.
